configure_file(
  ${CMAKE_SOURCE_DIR}/config.h.in
  ${CMAKE_BINARY_DIR}/config.h
  )

add_subdirectory(external)

include(ExternalProject)
ExternalProject_Add(${PROJECT_NAME}_core
  DEPENDS
    mrcpp_external
    getkw_external
    xcfun_external
  SOURCE_DIR
    ${PROJECT_SOURCE_DIR}/mrchem
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_STANDARD=11
    -DCMAKE_CXX_EXTENSIONS=OFF
    -DCMAKE_CXX_STANDARD_REQUIRED=ON
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCONFIG_H_LOCATION=${CMAKE_BINARY_DIR}
    -DEigen3_DIR=${Eigen3_DIR}
    -DMRCPP_DIR=${MRCPP_DIR}
    -DXCFun_DIR=${XCFun_DIR}
    -Dgetkw_DIR=${getkw_DIR}
    -DPYTHON_SITE_INSTALL_DIR=${PYTHON_SITE_INSTALL_DIR}
  CMAKE_CACHE_ARGS
    -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
    -DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}
  BUILD_ALWAYS
    1
  INSTALL_COMMAND
    DESTDIR=${CMAKE_BINARY_DIR}/stage ${CMAKE_MAKE_PROGRAM} install
  )

add_subdirectory(pilot)
