#!/usr/bin/env python3

import sys
from pathlib import Path

FILE = Path(__file__).resolve()
sys.path.append(str(FILE.parents[1]))

from tester import *  # isort:skip

options = script_cli()

filters = {
    SUM_OCCUPIED: rel_tolerance(1.0e-6),
    E_KIN: rel_tolerance(1.0e-6),
    E_EN: rel_tolerance(1.0e-6),
    E_EE: rel_tolerance(1.0e-6),
    E_X: rel_tolerance(1.0e-6),
    E_XC: rel_tolerance(1.0e-6),
    E_EEXT: rel_tolerance(1.0e-6),
    E_NEXT: rel_tolerance(1.0e-6),
    E_EL: rel_tolerance(1.0e-6),
    EXCITAION_ENERGY(1): rel_tolerance(1.0e-4),
    EXCITAION_ENERGY(2): rel_tolerance(1.0e-4),
}

ierr = run(options, input_file="h2", filters=filters, extra_args=["--json"])

sys.exit(ierr)
