version: 2
jobs:
  build:
    docker:
      - image: devcafe/ubuntu16.04-intel2018.1
    steps:
      - checkout:
         - post:
           - git submodule sync --recursive
           - git submodule update --recursive --init
      - run:
          name: Configure MRChem
          command: python ./setup --enable-unit-tests --type=release --cxx=icpc --omp 
      - run:
          name: Build MRChem
          command: cmake --build build --target install -- VERBOSE=1
