version: 2
jobs:
  build:
    docker:
      - image: devcafe/ubuntu16.04-intel2018.1
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
