name: All hail Minazo bot

on: pull_request

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
        working-directory: '.github'
 
    - name: Install clang-format
      run: sudo apt-get -y install clang-format
    
    - name: Run Danger
      env:
        DANGER_GITHUB_API_TOKEN: 0f8e593f9b3cb43e20657052785715081537661b
      run: BUNDLE_GEMFILE=.github/Gemfile bundle exec danger --dangerfile=.github/Dangerfile
