name: All hail Minazo bot

on: pull_request
      
jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'  # if only run pull request when multiple trigger workflow
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('.github/Gemfile') }} # change your gemfile path
        restore-keys: |
          ${{ runner.os }}-gems-
 
    - run: |
        sudo apt-get -y install clang-format
        bundle install --gemfile=.github/Gemfile
        BUNDLE_GEMFILE=.github/Gemfile bundle exec danger --dangerfile=.github/Dangerfile
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
