name: All hail Minazo bot

on: pull_request
      
jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'  # if only run pull request when multiple trigger workflow
    steps:
    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: mrchem-minazo
          environment-file: .github/mrchem-minazo.yml
          channel-priority: true
          python-version: 3.6

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile') }} # change your gemfile path
        restore-keys: |
          ${{ runner.os }}-gems-

    - uses: MeilCli/danger-action@v5
      with:
        plugins_file: '.github/Gemfile'
        install_path: 'vendor/bundle'
        danger_file: '.github/Dangerfile'
        danger_id: 'danger-pr'
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
