name: All hail Minazo bot

on: pull_request

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            

jobs:
  danger:
    runs-on: ubuntu-latest
    if: github.event_name  == 'pull_request'  # if only run pull request when multiple trigger workflow
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
        working-directory: '.github'

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('.github/Gemfile') }} # change your gemfile path
        restore-keys: |
          ${{ runner.os }}-gems-
 
    - run: |
        sudo apt-get -y install clang-format
        bundle install #--gemfile=.github/Gemfile
        #BUNDLE_GEMFILE=.github/Gemfile 
        bundle exec danger --dangerfile=.github/Dangerfile
